config/routes.rb
Forespeak::Application.routes.draw do
  
  get "users/index"

  get "users/confirm"

  resources :roles

  resources :user_sessions

  match '/' => 'root#index' ,:as => :root
  match 'login' , :controller => 'user_sessions', :action => 'new', :as => :login
  match 'logout', :controller => 'user_sessions', :action => 'destroy', :as => :logout

  resources :users
  resources :markets
  
  match '/resupply' => 'users#resupply'

  match '/buy' => 'markets#buy'
  match '/sell' => 'markets#sell'
  
  match '/markets/:id/updates/:position_id' => 'markets#updates'
  
  resources :market_management, :module => 'admin', :path => "/admin/markets"
  match '/admin/markets/close' => 'admin/market_management#close'

  match '/admin/users' => 'admin/users#index'
  match '/admin/users/confirm' => 'admin/users#confirm'
  match '/admin/users/unconfirm' => 'admin/users#unconfirm'
  
  

end

app/controllers/admin/market_management_controller.rb
class Admin::MarketManagementController < ApplicationController
  
  before_filter :require_admin_user
  
  def index
    @markets = Market.all
  end 

  def new
    @market = Market.new
    3.times { @market.outcomes.build }
  end
  
  def create
    # todo: needs test
    @market = Market.new(params[:market])
    @market.start_date = DateTime.civil(params[:start_date][:year].to_i, 
      params[:start_date][:month].to_i, 
      params[:start_date][:day].to_i,
      params[:start_date][:hour].to_i,
      params[:start_date][:minute].to_i,
      0,
      Rational(-6, 24)
      )
    @market.last_trade_allowed_date = DateTime.civil(params[:last_trade_allowed_date][:year].to_i,
      params[:last_trade_allowed_date][:month].to_i, 
      params[:last_trade_allowed_date][:day].to_i,
      params[:last_trade_allowed_date][:hour].to_i,
      params[:last_trade_allowed_date][:minute].to_i,
      0,
      Rational(-6, 24)
      )
    

    if @market.save
      flash[:notice]  = 'Successfully created market'
      redirect_to market_management_path(@market)
    else
      render :action => 'new'
    end
  end

  def show
    @market = Market.find(params[:id])
  end 
  # todo: needs test....also should be in outcome, not here
  def close
    outcome = Outcome.find(params[:outcome_id])
    
    market = outcome.market
    if market.nil? || ! market.end_date.nil?
      # todo: test
      flash[:error] = "Market has already be closed"
    end
    
    positions = outcome.all_user_positions
    
    positions.each do |position|
      user = position.user
      user.cash = user.cash + (position.total_user_shares * 100)
      user.save
    end
    
    market.end_date = Time.now
    market.save

    redirect_to market_management_index_path
  end
  
end

app/helpers/admin/market_management_helper.rb
module Admin::MarketManagementHelper
end

app/views/admin/market_management/_form.html.haml
= form_for @market, :as => :market, :url => { :action => "create" }, :html => {:class => "nifty_form"} do |f|
  =render "shared/error_messages", :target => @market


  .p 
    Name: 
    = f.text_field :name
  .p 
    Start Date: 
    = select_datetime DateTime.now , :prefix => :start_date


  .p 
    Last trade allowed date: 
    = select_datetime DateTime.now.to_time.advance(:days => 10).to_datetime, :prefix => :last_trade_allowed_date

  - f.fields_for :outcomes do |builder|
    = render "outcome_fields", :f => builder
  .p
    = link_to_add_fields "Add Outcome", f, :outcomes
  
  = submit_tag "Create"

app/views/admin/market_management/_outcome_fields.html.haml
.fields
  = f.label :description, "Description"
  = f.text_field :description
  = f.hidden_field :_destroy
  = link_to_remove_fields "remove", f

app/views/admin/market_management/index.html.haml
- @markets.each do |market|
  .span-24.market
    .span-10
      = market.name
    .span-3
      = market.start_date
    .span-4
      = market.last_trade_allowed_date.in_time_zone("Central Time (US & Canada)").strftime("%m/%d/%Y %H:%M") 
    .span-4.last
      - if market.end_date.nil?
        = link_to "Close market", market_management_path(market)
      - else
        Closed
      
= link_to "Create market", new_market_management_path

app/views/admin/market_management/new.html.haml
= render 'form'

app/views/admin/market_management/show.html.haml
.span-24.market

  .span-9
    .name
      = @market.name

    .start-date
      Start Date
      = @market.start_date

    .end-date
      End Date
      = @market.end_date
      
    .last-trade-date
      Last trade allowed
      = @market.last_trade_allowed_date
    
  .span-15.last
    - if @market.end_date.nil?
      %table.outcome
        %th Outcomes
        %th Sell Price
        %th Buy Price
        %th Total Shares Purchased
        %th
      
        - @market.outcomes.each do |outcome|
          %tr
            %td= outcome.description
            %td= "%0.4f" % outcome.sell_price
            %td= "%0.4f" % outcome.buy_price
            %td
              = outcome.shares_purchased 
            %td
              = form_tag :controller => "market_management", :action => "close", :method => "post" do
                = hidden_field_tag :outcome_id, outcome.id          
                = submit_tag "Select outcome"