config/routes.rb
Forespeak::Application.routes.draw do
  
  get "users/index"

  get "users/confirm"

  resources :roles

  resources :user_sessions

  match '/' => 'root#index' ,:as => :root
  match 'login' , :controller => 'user_sessions', :action => 'new', :as => :login
  match 'logout', :controller => 'user_sessions', :action => 'destroy', :as => :logout

  resources :users
  resources :markets
  
  match '/resupply' => 'users#resupply'

  match '/buy' => 'markets#buy'
  match '/sell' => 'markets#sell'
  
  match '/markets/:id/updates/:position_id' => 'markets#updates'
  
  resources :market_management, :module => 'admin', :path => "/admin/markets"
  match '/admin/markets/close' => 'admin/market_management#close'

  match '/admin/users' => 'admin/users#index'
  match '/admin/users/confirm' => 'admin/users#confirm'
  match '/admin/users/unconfirm' => 'admin/users#unconfirm'
  
  

end

app/models/role.rb
class Role < ActiveRecord::Base
  
  has_many :assignments
  has_many :users, :through => :assignments
    
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.xml
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.xml
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.xml
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.xml
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to(@role, :notice => 'Role was successfully created.') }
        format.xml  { render :xml => @role, :status => :created, :location => @role }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.xml
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to(@role, :notice => 'Role was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.xml
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to(roles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
= form_for @role do |f|
  -if @role.errors.any?
    #error_explanation
      %h2= "#{pluralize(@role.errors.count, "error")} prohibited this role from being saved:"
      %ul
        - @role.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/roles/edit.html.haml
%h1 Editing role

= render 'form'

= link_to 'Show', @role
\|
= link_to 'Back', roles_path

app/views/roles/index.html.haml
%h1 Listing roles

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @roles.each do |role|
    %tr
      %td= role.name
      %td= link_to 'Show', role
      %td= link_to 'Edit', edit_role_path(role)
      %td= link_to 'Destroy', role, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Role', new_role_path

app/views/roles/new.html.haml
%h1 New role

= render 'form'

= link_to 'Back', roles_path

app/views/roles/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @role.name

= link_to 'Edit', edit_role_path(@role)
\|
= link_to 'Back', roles_path